name: coverall
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go test -v -coverprofile=profile.cov ./...
      
      - name: send coveralls
      - uses: coverallsapp/github-action@v2
        with:
          path-to-profile: profile.cov
            
